export interface Supplement {
  id: string; // Уникальный идентификатор
  name: string; // Полноценное название товара
  brand: string;
  price: number;
  servings: number; // Сколько ВСЕГО порций в банке (нужно для расчета дней)
  dosagePerServing: string; // например, "500mg"
  suggestedDaily: number;   // порций в день (обычно 1 или 2)
  productUrl: string; // Прямая ссылка на товар
  category: 'Focus' | 'Sleep' | 'Energy' | 'Longevity' | 'Foundation' | 'Immune';
  subType: 'magnesium' | 'theanine' | 'curcumin' | 'vitamin-c' | 'multivitamin' | 'quercetin' | 'coq10' | 'omega-3' | 'caffeine' | 'vitamin-d3-k2' | 'zinc' | 'melatonin' | 'ashwagandha';   // Конкретный тип вещества (например, 'magnesium', 'caffeine') — ЭТО КЛЮЧЕВОЕ ПОЛЕ ДЛЯ АЛЕРТОВ!  
  description: string;
  isAvailable: boolean;
  imageFront: string; // Фас
  imageBack: string;  // Состав
  
}

export const SUPPLEMENTS: Supplement[] = [
  {
    id: "CGN-01901",
    name: "Magnesium Glycinate",
    brand: "California Gold Nutrition",
    price: 9.22,
    servings: 30,
    dosagePerServing: "200mg",
    suggestedDaily: 1,
    productUrl: "https://iherb.com/pr/california-gold-nutrition-magnesium-bisglycinate-chelate-albion-traacs-60-veggie-capsules-100-mg-per-capsule/103273",
    category: 'Sleep',
    subType: 'magnesium',
    description: "High-absorption magnesium bisglycinate chelate. Supports relaxation, muscle health, and sleep quality.",
    isAvailable: true,
    imageFront: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/cgn/cgn01901/l/77.jpg",
    imageBack: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/cgn/cgn01901/l/83.jpg"
  },
  {
    id: "CGN-01902",
    name: "Magnesium Glycinate",
    brand: "California Gold Nutrition",
    price: 28.42,
    servings: 120,
    dosagePerServing: "200mg",
    suggestedDaily: 1,
    productUrl: "https://iherb.com/pr/california-gold-nutrition-magnesium-bisglycinate-chelate-albion-traacs-240-veggie-capsules-100-mg-per-capsule/103274",
    category: 'Sleep',
    subType: 'magnesium',
    description: "High-absorption magnesium bisglycinate chelate. Supports relaxation, muscle health, and sleep quality.",
    isAvailable: true,
    imageFront: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/cgn/cgn01902/l/106.jpg",
    imageBack: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/cgn/cgn01902/l/111.jpg"
  },
  {
    id: "DRB-00025",
    name: "Magnesium Lysinate Glycinate, Chelated",
    brand: "Doctor's Best",
    price: 12.06,
    servings: 60,
    dosagePerServing: "200mg",
    suggestedDaily: 1,
    productUrl: "https://iherb.com/pr/doctor-s-best-high-absorption-magnesium-120-tablets-100-mg-per-tablet/15",
    category: 'Sleep',
    subType: 'magnesium',
    description: "Supports muscle relaxation, nerve function, and sleep quality with enhanced absorption, making it effective for maintaining a balanced mood and overall bodily functions.",
    isAvailable: true,
    imageFront: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/drb/drb00025/g/124.jpg",
    imageBack: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/drb/drb00025/l/129.jpg"
  },
  {
    id: "DRB-00087",
    name: "Magnesium Lysinate Glycinate, Chelated",
    brand: "Doctor's Best",
    price: 22.90,
    servings: 120,
    
    dosagePerServing: "200mg",
    suggestedDaily: 1,
    productUrl: "https://iherb.com/pr/doctor-s-best-high-absorption-magnesium-lysinate-glycinate-chelated-albion-traacs-240-tablets-100-mg-per-tablet/16567",
    category: 'Sleep',
    subType: 'magnesium',
    description: "Supports muscle relaxation, nerve function, and sleep quality with enhanced absorption, making it effective for maintaining a balanced mood and overall bodily functions.",
    isAvailable: true,
    imageFront: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/drb/drb00087/g/214.jpg",
    imageBack: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/drb/drb00087/l/219.jpg"
  },
  {
    id: "NOW-01284",
    name: "Magnesium Glycinate With BioPerine®",
    brand: "NOW Foods",
    price: 10.06,
    servings: 30,
    dosagePerServing: "200mg",
    suggestedDaily: 1,
    productUrl: "https://iherb.com/pr/now-foods-magnesium-glycinate-with-bioperine-60-veg-capsules/144961",
    category: 'Sleep',
    subType: 'magnesium',
    description: "Supports nervous system function and energy production with a highly absorbable form of magnesium, enhanced by BioPerine® for improved absorption.",
    isAvailable: true,
    imageFront: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/now/now01284/g/8.jpg",
    imageBack: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/now/now01284/l/13.jpg"
  },
  {
    id: "NOW-01287",
    name: "Magnesium Glycinate With BioPerine®",
    brand: "NOW Foods",
    price: 21.32,
    servings: 90,
    dosagePerServing: "200mg",
    suggestedDaily: 1,
    productUrl: "https://iherb.com/pr/now-foods-magnesium-glycinate-with-bioperine-180-veg-capsules/143369",
    category: 'Sleep',
    subType: 'magnesium',
    description: "Supports nervous system function and energy production with a highly absorbable form of magnesium, enhanced by BioPerine® for improved absorption.",
    isAvailable: true,
    imageFront: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/now/now01287/g/8.jpg",
    imageBack: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/now/now01287/l/10.jpg"
  },
  {
    id: "NOW-00147",
    name: "L-Theanine",
    brand: "Now Foods",
    price: 17.45,
    servings: 60,
    dosagePerServing: "200mg",
    suggestedDaily: 1,
    productUrl: "https://iherb.com/pr/now-foods-l-theanine-60-veg-capsules/6916",
    category: 'Focus',
    subType: 'theanine',
    description: "Promotes relaxation without drowsiness. Helps maintain focus and mental clarity during stress.",
    isAvailable: true,
    imageFront: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/now/now00147/g/36.jpg",
    imageBack: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/now/now00147/l/41.jpg"
  },
  {
    id: "NOW-00148",
    name: "L-Theanine",
    brand: "Now Foods",
    price: 26.48,
    servings: 120,
    dosagePerServing: "200mg",
    suggestedDaily: 1,
    productUrl: "https://iherb.com/pr/now-foods-l-theanine-120-veg-capsules/54096",
    category: 'Focus',
    subType: 'theanine',
    description: "Promotes relaxation without drowsiness. Helps maintain focus and mental clarity during stress.",
    isAvailable: true,
    imageFront: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/now/now00148/g/32.jpg",
    imageBack: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/now/now00148/l/38.jpg"
  },
  {
    id: "CGN-01242",
    name: "L-Theanine",
    brand: "California Gold Nutrition",
    price: 10.06,
    servings: 60,
    dosagePerServing: "200mg",
    suggestedDaily: 1,
    productUrl: "https://iherb.com/pr/california-gold-nutrition-l-theanine-featuring-alphawave-200-mg-60-veggie-capsules/83280",
    category: 'Focus',
    subType: 'theanine',
    description: "Promotes relaxation with a patented form of L-Theanine, designed to help reduce stress and enhance calmness in daily life.",
    isAvailable: true,
    imageFront: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/cgn/cgn01242/g/171.jpg",
    imageBack: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/cgn/cgn01242/l/176.jpg"
  },
  {
    id: "NCS-67720",
    name: "L-Theanine",
    brand: "Nutricost",
    price: 5.47,
    servings: 30,
    dosagePerServing: "200mg",
    suggestedDaily: 1,
    productUrl: "https://iherb.com/pr/nutricost-l-theanine-200-mg-30-capsules/145345",
    category: 'Focus',
    subType: 'theanine',
    description: "Supports relaxation and mental clarity, making it suitable for those seeking to reduce stress and enhance focus throughout their day.",
    isAvailable: true,
    imageFront: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/ncs/ncs67720/g/8.jpg",
    imageBack: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/ncs/ncs67720/l/13.jpg"
  },
  {
    id: "NCS-67937",
    name: "L-Theanine",
    brand: "Nutricost",
    price: 8.64,
    servings: 120,
    dosagePerServing: "200mg",
    suggestedDaily: 1,
    productUrl: "https://iherb.com/pr/nutricost-l-theanine-200-mg-120-capsules/140230",
    category: 'Focus',
    subType: 'theanine',
    description: "Supports relaxation and mental clarity, making it suitable for those seeking to reduce stress and enhance focus throughout their day.",
    isAvailable: true,
    imageFront: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/ncs/ncs67937/g/32.jpg",
    imageBack: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/ncs/ncs67937/l/37.jpg"
  },
  {
    id: "CGN-00940",
    name: "Curcumin C3 Complex",
    brand: "California Gold Nutrition",
    price: 34.90,
    servings: 120,
    dosagePerServing: "500mg",
    suggestedDaily: 1,
    productUrl: "https://iherb.com/pr/california-gold-nutrition-curcumin-c3-complex-with-bioperine-black-pepper-extract-turmeric-curcumin-complex-enhanced-bioavailablity-120-veggie-capsules/60047",
    category: 'Foundation',
    subType: 'curcumin',
    description: "Supports immune function and provides antioxidant benefits, promoting heart and joint health with enhanced absorption from black pepper extract.",
    isAvailable: true,
    imageFront: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/cgn/cgn00940/g/184.jpg",
    imageBack: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/cgn/cgn00940/l/189.jpg"
  },
  {
    id: "LKN-02002",
    name: "Curcumin 95",
    brand: "California Gold Nutrition",
    price: 7.94,
    servings: 30,
    dosagePerServing: "500mg",
    suggestedDaily: 1,
    productUrl: "https://iherb.com/pr/california-gold-nutrition-curcumin-95-30-veggie-capsules-500-mg-per-capsule/105621",
    category: 'Foundation',
    subType: 'curcumin',
    description: "Supports immune function and provides antioxidant benefits, promoting heart and joint health with enhanced absorption from black pepper extract.",
    isAvailable: true,
    imageFront: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/lkn/lkn02002/g/74.jpg",
    imageBack: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/lkn/lkn02002/l/79.jpg"
  },
  {
    id: "SPN-02427",
    name: "Turmeric Curcumin Phytosome Meriva®",
    brand: "California Gold Nutrition",
    price: 24.70,
    servings: 60,
    dosagePerServing: "500mg",
    suggestedDaily: 1,
    productUrl: "https://iherb.com/pr/california-gold-nutrition-turmeric-curcumin-phytosome-meriva-500-mg-60-veggie-capsules/137785",
    category: 'Foundation',
    subType: 'curcumin',
    description: "Supports joint, bone, and kidney health with a patented formulation that enhances absorption, featuring high levels of Demethoxycurcumin for effective benefits.",
    isAvailable: true,
    imageFront: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/spn/spn02427/g/147.jpg",
    imageBack: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/spn/spn02427/l/143.jpg"
  },
  {
    id: "LKN-01410",
    name: "Vitamin C",
    brand: "California Gold Nutrition",
    price: 34.39,
    servings: 365,
    dosagePerServing: "1000mg",
    suggestedDaily: 1,
    productUrl: "https://iherb.com/pr/california-gold-nutrition-vitamin-c-quali-c-1-000-mg-60-veggie-capsules/96338",
    category: 'Foundation',
    subType: 'vitamin-c',
    description: "Supports joint health and antioxidant function with a specialized formula that enhances nutrient absorption, promoting cellular integrity and liver health.",
    isAvailable: true,
    imageFront: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/lkn/lkn01410/g/98.jpg",
    imageBack: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/lkn/lkn01410/l/103.jpg"
  },
  {
    id: "NOW-00690",
    name: "C-1000",
    brand: "NOW Foods",
    price: 10.06,
    servings: 100,
    dosagePerServing: "1000mg",
    suggestedDaily: 1,
    productUrl: "https://iherb.com/pr/now-foods-c-1000-100-veg-capsules/39671",
    category: 'Foundation',
    subType: 'vitamin-c',
    description: "Supports immune health and collagen production, while providing antioxidant benefits. Enhanced with bioflavonoids for improved nutrient utilization.",
    isAvailable: true,
    imageFront: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/now/now00690/g/58.jpg",
    imageBack: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/now/now00690/l/64.jpg"
  },
    {
    id: "NOW-03070",
    name: "Quercetin with Bromelain",
    brand: "NOW Foods",
    price: 26.86,
    servings: 60,
    dosagePerServing: "800mg",
    suggestedDaily: 2,
    productUrl: "https://iherb.com/pr/now-foods-quercetin-with-bromelain-120-veg-capsules/330",
    category: 'Longevity',
    subType: 'quercetin',
    description: "Supports healthy seasonal immune function and respiratory health, combining quercetin and bromelain for balanced immune response to environmental challenges.",
    isAvailable: true,
    imageFront: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/now/now03070/g/50.jpg",
    imageBack: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/now/now03070/l/53.jpg"
  },
  {
    id: "NCS-67326",
    name: "Quercetin",
    brand: "Nutricost",
    price: 21.08,
    servings: 60,
    dosagePerServing: "1000mg",
    suggestedDaily: 1,
    productUrl: "https://iherb.com/pr/nutricost-quercetin-120-capsules-500-mg-per-capsule/135541",
    category: 'Longevity',
    subType: 'quercetin',
    description: "Supports healthy seasonal immune function and respiratory health, combining quercetin and bromelain for balanced immune response to environmental challenges.",
    isAvailable: true,
    imageFront: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/ncs/ncs67326/g/8.jpg",
    imageBack: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/ncs/ncs67326/l/13.jpg"
  },
  {
    id: "NOW-03352",
    name: "Energy Extreme",
    brand: "NOW Foods",
    price: 20.14,
    servings: 45,
    dosagePerServing: "1000mg",
    suggestedDaily: 1,
    productUrl: "https://iherb.com/pr/now-foods-sports-energy-extreme-90-capsules/63103",
    category: 'Energy',
    subType: 'multivitamin',
    description: "Supports healthy seasonal immune function and respiratory health, combining quercetin and bromelain for balanced immune response to environmental challenges.",
    isAvailable: true,
    imageFront: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/now/now03352/g/58.jpg",
    imageBack: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/now/now03352/l/63.jpg"
  },
  {
    id: "NOW-01995",
    name: "Sustained Energy",
    brand: "NOW Foods",
    price: 20.14,
    servings: 45,
    dosagePerServing: "1000mg",
    suggestedDaily: 1,
    productUrl: "https://iherb.com/pr/now-foods-sustained-energy-90-veg-capsules/131361",
    category: 'Energy',
    subType: 'multivitamin',
    description: "Supports sustained energy production and mental alertness with a blend of B vitamins and caffeine, designed for those seeking prolonged vitality and focus.",
    isAvailable: true,
    imageFront: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/now/now01995/g/12.jpg",
    imageBack: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/now/now01995/l/18.jpg"
  },
  {
    id: "NOW-03326",
    name: "Energy",
    brand: "NOW Foods",
    price: 18.80,
    servings: 45,
    dosagePerServing: "1000mg",
    suggestedDaily: 1,
    productUrl: "https://iherb.com/pr/now-foods-energy-90-veg-capsules/571",
    category: 'Energy',
    subType: 'multivitamin',
    description: "Supports energy production and adrenal function with a blend of B Vitamins, Green Tea, and Panax Ginseng, promoting metabolic energy and vitality.",
    isAvailable: true,
    imageFront: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/now/now03326/g/53.jpg",
    imageBack: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/now/now03326/l/59.jpg"
  },
  {
    id: "NOW-01661",
    name: "Ultra Omega-3 Fish Oil",
    brand: "NOW Foods",
    price: 18.80,
    servings: 90,
    dosagePerServing: "500mg EPA / 250mg DHA",
    suggestedDaily: 1,
    productUrl: "https://iherb.com/pr/now-foods-ultra-omega-3-fish-oil-90-softgels/76073",
    category: 'Foundation',
    subType: 'omega-3',
    description: "Molecularly distilled cardiovascular support. Helps maintain brain health, joint flexibility, and systemic inflammatory balance.",
    isAvailable: true,
    imageFront: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/now/now01661/g/36.jpg",
    imageBack: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/now/now01661/l/42.jpg"
  },
  {
    id: "NOW-01662",
    name: "Ultra Omega-3 Fish Oil",
    brand: "NOW Foods",
    price: 37.10,
    servings: 180,
    dosagePerServing: "500mg EPA / 250mg DHA",
    suggestedDaily: 1,
    productUrl: "https://iherb.com/pr/now-foods-ultra-omega-3-fish-oil-180-softgels/8341",
    category: 'Foundation',
    subType: 'omega-3',
    description: "Molecularly distilled cardiovascular support. Helps maintain brain health, joint flexibility, and systemic inflammatory balance.",
    isAvailable: true,
    imageFront: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/now/now01662/g/76.jpg",
    imageBack: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/now/now01662/l/81.jpg"
  },
  {
    id: "NOW-01652",
    name: "Omega-3 Fish Oil, 200 Softgels",
    brand: "NOW Foods",
    price: 17.61,
    servings: 100,
    dosagePerServing: "360mg EPA / 240mg DHA",
    suggestedDaily: 1,
    productUrl: "https://iherb.com/pr/now-foods-omega-3-fish-oil-200-softgels/323",
    category: 'Foundation',
    subType: 'omega-3',
    description: "Molecularly distilled cardiovascular support. Helps maintain brain health, joint flexibility, and systemic inflammatory balance.",
    isAvailable: true,
    imageFront: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/now/now01652/g/68.jpg",
    imageBack: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/now/now01652/l/73.jpg"
  },
  {
    id: "NOW-01650",
    name: "Omega-3 Fish Oil, 100 Softgels",
    brand: "NOW Foods",
    price: 8.72,
    servings: 50,
    dosagePerServing: "360mg EPA / 240mg DHA",
    suggestedDaily: 1,
    productUrl: "https://iherb.com/pr/now-foods-omega-3-fish-oil-1-000-mg-180-epa-120-dha-100-softgels/102333",
    category: 'Foundation',
    subType: 'omega-3',
    description: "Molecularly distilled cardiovascular support. Helps maintain brain health, joint flexibility, and systemic inflammatory balance.",
    isAvailable: true,
    imageFront: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/now/now01650/g/38.jpg",
    imageBack: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/now/now01650/l/41.jpg"
  },
  {
    id: "MLI-00952",
    name: "Omega-3 Premium Fish Oil",
    brand: "California Gold Nutrition",
    price: 12.20,
    servings: 50,
    dosagePerServing: "360mg EPA / 240mg DHA",
    suggestedDaily: 1,
    productUrl: "https://iherb.com/pr/california-gold-nutrition-omega-3-premium-fish-oil-100-fish-gelatin-softgels-1-100-mg-per-softgel/62118",
    category: 'Foundation',
    subType: 'omega-3',
    description: "Molecularly distilled cardiovascular support. Helps maintain brain health, joint flexibility, and systemic inflammatory balance.",
    isAvailable: true,
    imageFront: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/mli/mli00952/g/392.jpg",
    imageBack: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/mli/mli00952/l/397.jpg"
  },
  {
    id: "NCS-67518",
    name: "Caffeine",
    brand: "Nutricost",
    price: 11.96,
    servings: 250,
    dosagePerServing: "200mg",
    suggestedDaily: 1,
    productUrl: "https://iherb.com/pr/nutricost-caffeine-200-mg-250-capsules/139405",
    category: 'Energy',
    subType: 'caffeine',
    description: "Provides clean energy and mental alertness. Best combined with L-Theanine to eliminate jitteriness and crash.",
    isAvailable: true,
    imageFront: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/ncs/ncs67517/g/8.jpg",
    imageBack: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/ncs/ncs67517/l/11.jpg"
  },
  {
    id: "FOA-66273",
    name: "Caffeine",
    brand: "Force Factor",
    price: 17.84,
    servings: 250,
    dosagePerServing: "200mg",
    suggestedDaily: 1,
    productUrl: "https://iherb.com/pr/force-factor-caffeine-200-mg-250-tablets/154063",
    category: 'Energy',
    subType: 'caffeine',
    description: "Provides clean energy and mental alertness. Best combined with L-Theanine to eliminate jitteriness and crash.",
    isAvailable: true,
    imageFront: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/foa/foa66273/g/8.jpg",
    imageBack: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/foa/foa66273/l/14.jpg"
  },
  {
    id: "CGN-02333",
    name: "Vitamin D3 + K2",
    brand: "California Gold Nutrition",
    price: 16.20,
    servings: 180,
    dosagePerServing: "125mcg D3 / 120mcg K2",
    suggestedDaily: 1,
    productUrl: "https://iherb.com/pr/california-gold-nutrition-vitamin-d3-k2-as-mk-7-180-veggie-capsules/124745",
    category: 'Foundation',
    subType: 'vitamin-d3-k2',
    description: "Synergistic blend for bone and cardiovascular health. Vitamin K2 guides Calcium into bones where it belongs.",
    isAvailable: true,
    imageFront: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/cgn/cgn02333/g/63.jpg",
    imageBack: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/cgn/cgn02333/l/68.jpg"
  },
  {
    id: "CGN-02332",
    name: "Vitamin D3 + K2",
    brand: "California Gold Nutrition",
    price: 9.22,
    servings: 60,
    dosagePerServing: "125mcg D3 / 120mcg K2",
    suggestedDaily: 1,
    productUrl: "https://iherb.com/pr/california-gold-nutrition-vitamin-d3-k2-as-mk-7-60-veggie-capsules/124743",
    category: 'Foundation',
    subType: 'vitamin-d3-k2',
    description: "Synergistic blend for bone and cardiovascular health. Vitamin K2 guides Calcium into bones where it belongs.",
    isAvailable: true,
    imageFront: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/cgn/cgn02333/g/63.jpg",
    imageBack: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/cgn/cgn02333/l/68.jpg"
  },
  {
    id: "NOW-01552",
    name: "Zinc Picolinate",
    brand: "NOW Foods",
    price: 12.08,
    servings: 120,
    dosagePerServing: "50mg",
    suggestedDaily: 1,
    productUrl: "https://iherb.com/pr/now-foods-zinc-picolinate-50-mg-120-veg-capsules/878",
    category: 'Immune',
    subType: 'zinc',
    description: "Highly absorbable form of Zinc. Supports immune function, cellular health, and enzyme optimization.",
    isAvailable: true,
    imageFront: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/now/now01552/g/57.jpg",
    imageBack: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/now/now01552/l/62.jpg"
  },
  {
    id: "NOW-01550",
    name: "Zinc Picolinate",
    brand: "NOW Foods",
    price: 6.70,
    servings: 60,
    dosagePerServing: "50mg",
    suggestedDaily: 1,
    productUrl: "https://iherb.com/pr/now-foods-zinc-picolinate-50-mg-60-veg-capsules/117151",
    category: 'Immune',
    subType: 'zinc',
    description: "Highly absorbable form of Zinc. Supports immune function, cellular health, and enzyme optimization.",
    isAvailable: true,
    imageFront: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/now/now01550/g/31.jpg",
    imageBack: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/now/now01550/l/36.jpg"
  },
  {
    id: "NOW- NOW-01522",
    name: "Zinc",
    brand: "NOW Foods",
    price: 12.08,
    servings: 250,
    dosagePerServing: "50mg",
    suggestedDaily: 1,
    productUrl: "https://iherb.com/pr/now-foods-zinc-50-mg-250-tablets/883",
    category: 'Immune',
    subType: 'zinc',
    description: "Supports immune function, cellular health, and enzyme optimization.",
    isAvailable: true,
    imageFront: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/now/now01522/g/72.jpg",
    imageBack: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/now/now01522/l/77.jpg"
  },
  {
    id: "NOW- NOW-01520",
    name: "Zinc",
    brand: "NOW Foods",
    price: 6.03,
    servings: 100,
    dosagePerServing: "50mg",
    suggestedDaily: 1,
    productUrl: "https://iherb.com/pr/now-foods-zinc-50-mg-100-tablets/116598",
    category: 'Immune',
    subType: 'zinc',
    description: "Supports immune function, cellular health, and enzyme optimization.",
    isAvailable: true,
    imageFront: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/now/now01520/g/30.jpg",
    imageBack: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/now/now01520/l/35.jpg"
  },
  {
    id: "DRB-00573",
    name: "High Absorption Zinc Bisglycinate",
    brand: "Doctor's Best",
    price: 10.10,
    servings: 90,
    dosagePerServing: "50mg",
    suggestedDaily: 1,
    productUrl: "https://iherb.com/pr/doctor-s-best-high-absorption-zinc-bisglycinate-50-mg-90-veggie-caps/104165",
    category: 'Immune',
    subType: 'zinc',
    description: "Supports immune function, cellular health, and enzyme optimization.",
    isAvailable: true,
    imageFront: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/drb/drb00573/g/40.jpg",
    imageBack: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/drb/drb00573/l/45.jpg"
  },
  {
    id: "CEN-28032",
    name: "Zinc Citrate, 50 mg, 360 Tablets",
    brand: "21st Century",
    price: 9.84,
    servings: 360,
    dosagePerServing: "50mg",
    suggestedDaily: 1,
    productUrl: "https://iherb.com/pr/21st-century-zinc-citrate-50-mg-360-tablets/110923",
    category: 'Immune',
    subType: 'zinc',
    description: "Zinc is crucial for the immune system, acting as a cofactor for numerous enzymes involved in cellular function and antioxidant defense.",
    isAvailable: true,
    imageFront: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/cen/cen28032/g/24.jpg",
    imageBack: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/cen/cen28032/l/29.jpg"
  },
  {
    id: "CEN-28026",
    name: "Zinc Citrate, 50 mg, 60 Tablets",
    brand: "21st Century",
    price: 2.88,
    servings: 60,
    dosagePerServing: "50mg",
    suggestedDaily: 1,
    productUrl: "https://iherb.com/pr/21st-century-zinc-citrate-50-mg-60-tablets/104765",
    category: 'Immune',
    subType: 'zinc',
    description: "Zinc is crucial for the immune system, acting as a cofactor for numerous enzymes involved in cellular function and antioxidant defense.",
    isAvailable: true,
    imageFront: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/cen/cen28026/g/31.jpg",
    imageBack: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/cen/cen28026/l/37.jpg"
  },
  {
    id: "NOW-03254",
    name: "Melatonin, 3 mg, 180 Veg Capsules",
    brand: "NOW Foods",
    price: 10.06,
    servings:180,
    dosagePerServing: "3mg",
    suggestedDaily: 1,
    productUrl: "https://iherb.com/pr/now-foods-melatonin-3-mg-180-veg-capsules/328",
    category: 'Sleep',
    subType: 'melatonin',
    description: "Healthy sleep cycle support. Helps regulate the body's circadian rhythm and improves sleep quality.",
    isAvailable: true,
    imageFront: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/now/now03257/g/52.jpg",
    imageBack: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/now/now03257/l/57.jpg"
  },
  {
    id: "NOW-03255",
    name: "Melatonin, 3 mg, 60 Veg Capsules",
    brand: "NOW Foods",
    price: 4.68,
    servings:60,
    dosagePerServing: "3mg",
    suggestedDaily: 1,
    productUrl: "https://iherb.com/pr/now-foods-melatonin-3-mg-60-veg-capsules/14810",
    category: 'Sleep',
    subType: 'melatonin',
    description: "Healthy sleep cycle support. Helps regulate the body's circadian rhythm and improves sleep quality.",
    isAvailable: true,
    imageFront: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/now/now03255/g/54.jpg",
    imageBack: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/now/now03255/l/59.jpg"
  },
  {
    id: "CEN-21240",
    name: "Melatonin, 3 mg, 90 Tablets",
    brand: "21st Century",
    price: 3.71,
    servings:90,
    dosagePerServing: "3mg",
    suggestedDaily: 1,
    productUrl: "https://iherb.com/pr/21st-century-melatonin-3-mg-90-tablets/43880",
    category: 'Sleep',
    subType: 'melatonin',
    description: "Healthy sleep cycle support. Helps regulate the body's circadian rhythm and improves sleep quality.",
    isAvailable: true,
    imageFront: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/cen/cen21240/g/47.jpg",
    imageBack: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/cen/cen21240/l/53.jpg"
  },
  {
    id: "CEN-22721",
    name: "Melatonin, 3 mg, 200 Tablets",
    brand: "21st Century",
    price: 8.43,
    servings:200,
    dosagePerServing: "3mg",
    suggestedDaily: 1,
    productUrl: "https://iherb.com/pr/21st-century-melatonin-3-mg-200-tablets/14103",
    category: 'Sleep',
    subType: 'melatonin',
    description: "Healthy sleep cycle support. Helps regulate the body's circadian rhythm and improves sleep quality.",
    isAvailable: true,
    imageFront: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/cen/cen22721/v/58.jpg",
    imageBack: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/cen/cen22721/l/64.jpg"
  },
  {
    id: "NAP-47625",
    name: "Fast Acting Melatonin, 3 mg, 90 Tablets",
    brand: "NaturesPlus",
    price: 7.41,
    servings:90,
    dosagePerServing: "3mg",
    suggestedDaily: 1,
    productUrl: "https://iherb.com/pr/naturesplus-fast-acting-melatonin-3-mg-90-tablets/113990",
    category: 'Sleep',
    subType: 'melatonin',
    description: "Healthy sleep cycle support. Helps regulate the body's circadian rhythm and improves sleep quality.",
    isAvailable: true,
    imageFront: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/nap/nap47625/g/24.jpg",
    imageBack: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/nap/nap47625/l/32.jpg"
  },  
  {
    id: "NOW-04603",
    name: "AAshwagandha, 450 mg, 90 Veg Capsules",
    brand: "NOW Foods",
    price: 13.42,
    servings: 90,
    dosagePerServing: "450mg",
    suggestedDaily: 1,
    productUrl: "https://iherb.com/pr/now-foods-ashwagandha-standardized-extract-450-mg-90-veg-capsules/310",
    category: 'Focus',
    subType: 'ashwagandha',
    description: "Ayurvedic adaptogen that helps the body manage stress, lowers cortisol, and supports cognitive health.",
    isAvailable: true,
    imageFront: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/now/now04603/g/83.jpg",
    imageBack: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/now/now04603/l/88.jpg"
  },
  {
    id: "NOW-04593",
    name: "AAshwagandha 450 mg, 180 Veg Capsules",
    brand: "NOW Foods",
    price: 23.50,
    servings: 180,
    dosagePerServing: "450mg",
    suggestedDaily: 1,
    productUrl: "https://iherb.com/pr/now-foods-standardized-extract-ashwagandha-450-mg-180-veg-capsules/78203",
    category: 'Focus',
    subType: 'ashwagandha',
    description: "Ayurvedic adaptogen that helps the body manage stress, lowers cortisol, and supports cognitive health.",
    isAvailable: true,
    imageFront: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/now/now04593/g/27.jpg",
    imageBack: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/now/now04593/l/33.jpg"
  },
  {
    id: "SWV-14287",
    name: "Ashwagandha 450 mg, 60 Capsules",
    brand: "Swanson Vitamins",
    price: 6.20,
    servings: 60,
    dosagePerServing: "450mg",
    suggestedDaily: 1,
    productUrl: "https://iherb.com/pr/swanson-vitamins-ashwagandha-extract-standardized-450-mg-60-capsules/116341",
    category: 'Focus',
    subType: 'ashwagandha',
    description: "Ayurvedic adaptogen that helps the body manage stress, lowers cortisol, and supports cognitive health.",
    isAvailable: true,
    imageFront: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/swv/swv14287/g/40.jpg",
    imageBack: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/swv/swv14287/l/46.jpg"
  },
  {
    id: "CGN-01365",
    name: "Ashwagandha, 450 mg, 180 Veggie Capsules",
    brand: "California Gold Nutrition",
    price: 20.09,
    servings: 180,
    dosagePerServing: "450mg",
    suggestedDaily: 1,
    productUrl: "https://iherb.com/pr/california-gold-nutrition-ashwagandha-450-mg-180-veggie-capsules/89863",
    category: 'Focus',
    subType: 'ashwagandha',
    description: "Ayurvedic adaptogen that helps the body manage stress, lowers cortisol, and supports cognitive health.",
    isAvailable: true,
    imageFront: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/cgn/cgn01365/g/148.jpg",
    imageBack: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/cgn/cgn01365/l/153.jpg"
  },
  {
    id: "CEN-28071",
    name: "Ashwagandha 60 Veg Capsules (500 mg per Capsule)",
    brand: "21st Century",
    price: 13.46,
    servings: 60,
    dosagePerServing: "450mg",
    suggestedDaily: 1,
    productUrl: "https://iherb.com/pr/21st-century-ashwagandha-extract-standardized-60-vegetarian-capsules-500-mg-per-capsule/115013",
    category: 'Focus',
    subType: 'ashwagandha',
    description: "Ayurvedic adaptogen that helps the body manage stress, lowers cortisol, and supports cognitive health.",
    isAvailable: true,
    imageFront: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/cen/cen28071/g/30.jpg",
    imageBack: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/cen/cen28071/l/36.jpg"
  },
  {
    id: "NOW-04595",
    name: "Ashwagandha, 450 mg, 30 Veg Capsules",
    brand: "NOW Foods",
    price: 6.70,
    servings: 30,
    dosagePerServing: "450mg",
    suggestedDaily: 1,
    productUrl: "https://iherb.com/pr/now-foods-ashwagandha-450-mg-30-veg-capsules/156671",
    category: 'Focus',
    subType: 'ashwagandha',
    description: "Ayurvedic adaptogen that helps the body manage stress, lowers cortisol, and supports cognitive health.",
    isAvailable: true,
    imageFront: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/now/now04595/g/8.jpg",
    imageBack: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/now/now04595/l/13.jpg"
  },
  {
    id: "CGN-00944",
    name: "CoQ10, 100 mg, 120 Veggie Softgels",
    brand: "California Gold Nutrition",
    price: 21.48,
    servings: 120,
    dosagePerServing: "100mg",
    suggestedDaily: 1,
    productUrl: "https://iherb.com/pr/california-gold-nutrition-coq10-100-mg-120-veggie-softgels/61074",
    category: 'Foundation',
    subType: 'coq10',
    description: "Coenzyme Q10 is involved in the production of ATP, the primary energy carrier in cells, supporting mitochondrial function and energy production.",
    isAvailable: true,
    imageFront: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/cgn/cgn00944/g/198.jpg",
    imageBack: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/cgn/cgn00944/l/204.jpg"
  },

];

