export interface Supplement {
  id: string;
  name: string;
  brand: string;
  price: number;
  servings: number;
  productUrl: string; // Прямая ссылка на товар
  category: 'Focus' | 'Sleep' | 'Energy' | 'Longevity' | 'Foundation';
  subType: 'magnesium' | 'theanine' | 'curcumin' | 'vitamin-c' | 'multivitamin' | 'quercetin' | 'coq10' | 'omega-3';
  description: string;
  isAvailable: boolean;
  imageFront: string; // Фас
  imageBack: string;  // Состав
}

export const SUPPLEMENTS: Supplement[] = [
  {
    id: "CGN-01901",
    name: "Magnesium Glycinate",
    brand: "California Gold Nutrition",
    price: 9.22,
    servings: 30,
    productUrl: "https://iherb.com/pr/california-gold-nutrition-magnesium-bisglycinate-chelate-albion-traacs-60-veggie-capsules-100-mg-per-capsule/103273",
    category: 'Sleep',
    subType: 'magnesium',
    description: "High-absorption magnesium bisglycinate chelate. Supports relaxation, muscle health, and sleep quality.",
    isAvailable: true,
    imageFront: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/cgn/cgn01901/l/77.jpg",
    imageBack: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/cgn/cgn01901/l/83.jpg"
  },
  {
    id: "CGN-01902",
    name: "Magnesium Glycinate",
    brand: "California Gold Nutrition",
    price: 28.42,
    servings: 120,
    productUrl: "https://iherb.com/pr/california-gold-nutrition-magnesium-bisglycinate-chelate-albion-traacs-240-veggie-capsules-100-mg-per-capsule/103274",
    category: 'Sleep',
    subType: 'magnesium',
    description: "High-absorption magnesium bisglycinate chelate. Supports relaxation, muscle health, and sleep quality.",
    isAvailable: true,
    imageFront: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/cgn/cgn01902/l/106.jpg",
    imageBack: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/cgn/cgn01902/l/111.jpg"
  },
  {
    id: "DRB-00025",
    name: "Magnesium Lysinate Glycinate, Chelated",
    brand: "Doctor's Best",
    price: 12.06,
    servings: 60,
    productUrl: "https://iherb.com/pr/doctor-s-best-high-absorption-magnesium-120-tablets-100-mg-per-tablet/15",
    category: 'Sleep',
    subType: 'magnesium',
    description: "Supports muscle relaxation, nerve function, and sleep quality with enhanced absorption, making it effective for maintaining a balanced mood and overall bodily functions.",
    isAvailable: true,
    imageFront: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/drb/drb00025/g/124.jpg",
    imageBack: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/drb/drb00025/l/129.jpg"
  },
  {
    id: "DRB-00087",
    name: "Magnesium Lysinate Glycinate, Chelated",
    brand: "Doctor's Best",
    price: 22.90,
    servings: 120,
    productUrl: "https://iherb.com/pr/doctor-s-best-high-absorption-magnesium-lysinate-glycinate-chelated-albion-traacs-240-tablets-100-mg-per-tablet/16567",
    category: 'Sleep',
    subType: 'magnesium',
    description: "Supports muscle relaxation, nerve function, and sleep quality with enhanced absorption, making it effective for maintaining a balanced mood and overall bodily functions.",
    isAvailable: true,
    imageFront: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/drb/drb00087/g/214.jpg",
    imageBack: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/drb/drb00087/l/219.jpg"
  },
  {
    id: "NOW-01284",
    name: "Magnesium Glycinate With BioPerine®",
    brand: "NOW Foods",
    price: 10.06,
    servings: 30,
    productUrl: "https://iherb.com/pr/now-foods-magnesium-glycinate-with-bioperine-60-veg-capsules/144961",
    category: 'Sleep',
    subType: 'magnesium',
    description: "Supports nervous system function and energy production with a highly absorbable form of magnesium, enhanced by BioPerine® for improved absorption.",
    isAvailable: true,
    imageFront: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/now/now01284/g/8.jpg",
    imageBack: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/now/now01284/l/13.jpg"
  },
  {
    id: "NOW-01287",
    name: "Magnesium Glycinate With BioPerine®",
    brand: "NOW Foods",
    price: 21.32,
    servings: 90,
    productUrl: "https://iherb.com/pr/now-foods-magnesium-glycinate-with-bioperine-180-veg-capsules/143369",
    category: 'Sleep',
    subType: 'magnesium',
    description: "Supports nervous system function and energy production with a highly absorbable form of magnesium, enhanced by BioPerine® for improved absorption.",
    isAvailable: true,
    imageFront: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/now/now01287/g/8.jpg",
    imageBack: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/now/now01287/l/10.jpg"
  },
  {
    id: "NOW-00147",
    name: "L-Theanine",
    brand: "Now Foods",
    price: 17.45,
    servings: 60,
    productUrl: "https://iherb.com/pr/now-foods-l-theanine-60-veg-capsules/6916",
    category: 'Focus',
    subType: 'theanine',
    description: "Promotes relaxation without drowsiness. Helps maintain focus and mental clarity during stress.",
    isAvailable: true,
    imageFront: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/now/now00147/g/36.jpg",
    imageBack: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/now/now00147/l/41.jpg"
  },
  {
    id: "NOW-00148",
    name: "L-Theanine",
    brand: "Now Foods",
    price: 26.48,
    servings: 120,
    productUrl: "https://iherb.com/pr/now-foods-l-theanine-120-veg-capsules/54096",
    category: 'Focus',
    subType: 'theanine',
    description: "Promotes relaxation without drowsiness. Helps maintain focus and mental clarity during stress.",
    isAvailable: true,
    imageFront: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/now/now00148/g/32.jpg",
    imageBack: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/now/now00148/l/38.jpg"
  },
  {
    id: "CGN-01242",
    name: "L-Theanine",
    brand: "California Gold Nutrition",
    price: 10.06,
    servings: 60,
    productUrl: "https://iherb.com/pr/california-gold-nutrition-l-theanine-featuring-alphawave-200-mg-60-veggie-capsules/83280",
    category: 'Focus',
    subType: 'theanine',
    description: "Promotes relaxation with a patented form of L-Theanine, designed to help reduce stress and enhance calmness in daily life.",
    isAvailable: true,
    imageFront: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/cgn/cgn01242/g/171.jpg",
    imageBack: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/cgn/cgn01242/l/176.jpg"
  },
  {
    id: "NCS-67720",
    name: "L-Theanine",
    brand: "Nutricost",
    price: 5.47,
    servings: 30,
    productUrl: "https://iherb.com/pr/nutricost-l-theanine-200-mg-30-capsules/145345",
    category: 'Focus',
    subType: 'theanine',
    description: "Supports relaxation and mental clarity, making it suitable for those seeking to reduce stress and enhance focus throughout their day.",
    isAvailable: true,
    imageFront: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/ncs/ncs67720/g/8.jpg",
    imageBack: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/ncs/ncs67720/l/13.jpg"
  },
  {
    id: "NCS-67937",
    name: "L-Theanine",
    brand: "Nutricost",
    price: 8.64,
    servings: 120,
    productUrl: "https://iherb.com/pr/nutricost-l-theanine-200-mg-120-capsules/140230",
    category: 'Focus',
    subType: 'theanine',
    description: "Supports relaxation and mental clarity, making it suitable for those seeking to reduce stress and enhance focus throughout their day.",
    isAvailable: true,
    imageFront: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/ncs/ncs67937/g/32.jpg",
    imageBack: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/ncs/ncs67937/l/37.jpg"
  },
  {
    id: "CGN-00940",
    name: "Curcumin C3 Complex",
    brand: "California Gold Nutrition",
    price: 34.90,
    servings: 120,
    productUrl: "https://iherb.com/pr/california-gold-nutrition-curcumin-c3-complex-with-bioperine-black-pepper-extract-turmeric-curcumin-complex-enhanced-bioavailablity-120-veggie-capsules/60047",
    category: 'Foundation',
    subType: 'curcumin',
    description: "Supports immune function and provides antioxidant benefits, promoting heart and joint health with enhanced absorption from black pepper extract.",
    isAvailable: true,
    imageFront: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/cgn/cgn00940/g/184.jpg",
    imageBack: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/cgn/cgn00940/l/189.jpg"
  },
  {
    id: "LKN-02002",
    name: "Curcumin 95",
    brand: "California Gold Nutrition",
    price: 7.94,
    servings: 30,
    productUrl: "https://iherb.com/pr/california-gold-nutrition-curcumin-95-30-veggie-capsules-500-mg-per-capsule/105621",
    category: 'Foundation',
    subType: 'curcumin',
    description: "Supports immune function and provides antioxidant benefits, promoting heart and joint health with enhanced absorption from black pepper extract.",
    isAvailable: true,
    imageFront: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/lkn/lkn02002/g/74.jpg",
    imageBack: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/lkn/lkn02002/l/79.jpg"
  },
  {
    id: "SPN-02427",
    name: "Turmeric Curcumin Phytosome Meriva®",
    brand: "California Gold Nutrition",
    price: 24.70,
    servings: 60,
    productUrl: "https://iherb.com/pr/california-gold-nutrition-turmeric-curcumin-phytosome-meriva-500-mg-60-veggie-capsules/137785",
    category: 'Foundation',
    subType: 'curcumin',
    description: "Supports joint, bone, and kidney health with a patented formulation that enhances absorption, featuring high levels of Demethoxycurcumin for effective benefits.",
    isAvailable: true,
    imageFront: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/spn/spn02427/g/147.jpg",
    imageBack: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/spn/spn02427/l/143.jpg"
  },
  {
    id: "LKN-01410",
    name: "Vitamin C",
    brand: "California Gold Nutrition",
    price: 34.39,
    servings: 365,
    productUrl: "https://iherb.com/pr/california-gold-nutrition-vitamin-c-quali-c-1-000-mg-60-veggie-capsules/96338",
    category: 'Foundation',
    subType: 'vitamin-c',
    description: "Supports joint health and antioxidant function with a specialized formula that enhances nutrient absorption, promoting cellular integrity and liver health.",
    isAvailable: true,
    imageFront: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/lkn/lkn01410/g/98.jpg",
    imageBack: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/lkn/lkn01410/l/103.jpg"
  },
  {
    id: "NOW-00690",
    name: "C-1000",
    brand: "NOW Foods",
    price: 10.06,
    servings: 100,
    productUrl: "https://iherb.com/pr/now-foods-c-1000-100-veg-capsules/39671",
    category: 'Foundation',
    subType: 'vitamin-c',
    description: "Supports immune health and collagen production, while providing antioxidant benefits. Enhanced with bioflavonoids for improved nutrient utilization.",
    isAvailable: true,
    imageFront: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/now/now00690/g/58.jpg",
    imageBack: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/now/now00690/l/64.jpg"
  },
    {
    id: "NOW-03070",
    name: "Quercetin with Bromelain",
    brand: "NOW Foods",
    price: 26.86,
    servings: 60,
    productUrl: "https://iherb.com/pr/now-foods-quercetin-with-bromelain-120-veg-capsules/330",
    category: 'Longevity',
    subType: 'quercetin',
    description: "Supports healthy seasonal immune function and respiratory health, combining quercetin and bromelain for balanced immune response to environmental challenges.",
    isAvailable: true,
    imageFront: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/now/now03070/g/50.jpg",
    imageBack: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/now/now03070/l/53.jpg"
  },
  {
    id: "NCS-67326",
    name: "Quercetin",
    brand: "Nutricost",
    price: 21.08,
    servings: 60,
    productUrl: "https://iherb.com/pr/nutricost-quercetin-120-capsules-500-mg-per-capsule/135541",
    category: 'Longevity',
    subType: 'quercetin',
    description: "Supports healthy seasonal immune function and respiratory health, combining quercetin and bromelain for balanced immune response to environmental challenges.",
    isAvailable: true,
    imageFront: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/ncs/ncs67326/g/8.jpg",
    imageBack: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/ncs/ncs67326/l/13.jpg"
  },
  {
    id: "NOW-03352",
    name: "Energy Extreme",
    brand: "NOW Foods",
    price: 20.14,
    servings: 45,
    productUrl: "https://iherb.com/pr/now-foods-sports-energy-extreme-90-capsules/63103",
    category: 'Energy',
    subType: 'multivitamin',
    description: "Supports healthy seasonal immune function and respiratory health, combining quercetin and bromelain for balanced immune response to environmental challenges.",
    isAvailable: true,
    imageFront: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/now/now03352/g/58.jpg",
    imageBack: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/now/now03352/l/63.jpg"
  },
  {
    id: "NOW-01995",
    name: "Sustained Energy",
    brand: "NOW Foods",
    price: 20.14,
    servings: 45,
    productUrl: "https://iherb.com/pr/now-foods-sustained-energy-90-veg-capsules/131361",
    category: 'Energy',
    subType: 'multivitamin',
    description: "Supports sustained energy production and mental alertness with a blend of B vitamins and caffeine, designed for those seeking prolonged vitality and focus.",
    isAvailable: true,
    imageFront: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/now/now01995/g/12.jpg",
    imageBack: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/now/now01995/l/18.jpg"
  },
  {
    id: "NOW-03326",
    name: "Energy",
    brand: "NOW Foods",
    price: 18.80,
    servings: 45,
    productUrl: "https://iherb.com/pr/now-foods-energy-90-veg-capsules/571",
    category: 'Energy',
    subType: 'multivitamin',
    description: "Supports energy production and adrenal function with a blend of B Vitamins, Green Tea, and Panax Ginseng, promoting metabolic energy and vitality.",
    isAvailable: true,
    imageFront: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/now/now03326/g/53.jpg",
    imageBack: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/now/now03326/l/59.jpg"
  },
];

